issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - scopelint
        - funlen
        - maligned
        - paralleltest
        - testpackage
        - goerr113
        - varnamelen
    - path: github/client
      linters:
        - gosec

linters:
  enable-all: true
  disable:
    - lll
    - gochecknoglobals
    - gochecknoinits
    - typecheck
    - errcheck
    - godox
    - gomnd
    - wsl
    - exhaustivestruct
    - exhaustruct
    # should be enabled shortly
    - funlen
    - dupl
    - nlreturn
    - cyclop

linters-settings:
  govet:
    check-shadowing: false

  gofmt:
    simplify: true

  gocyclo:
    # minimal code complexity to report, 30 by default (we should lower it to around 15-17)
    min-complexity: 25

  misspell:
    locale: neutral

  goimports:
    local-prefixes: github.com/ppapapetrou76/virtual-assistant

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental

output:
  format: tab
